import { useState, useEffect } from 'react'
import Link from 'next/link'
import axios from 'axios'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [posts, setPosts] = useState([])
  const [timestamp, setTimestamp] = useState(new Date().getTime())

  useEffect(() => {
    getAllPosts()
    const interval = setInterval(() => {
      setTimestamp(new Date().getTime())
    }, 1000);
    return () => clearInterval(interval);
  }, [])

  const increaseTime = (id) => {
    axios.patch(`http://localhost:3000/posts/${id}/increment_count`)
         .then(getAllPosts)
  }

  const getAllPosts = async () => {
    return axios.get('http://localhost:3000/posts')
      .then((response) => {
        setPosts(response.data)
      })
      .catch((err) => {
        console.log(err);
      })
  }

  const expiresInSeconds = postExpiresAt => {
    return Math.floor((Date.parse(postExpiresAt) - timestamp) / 1000)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Basic Reddit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href="/new_post">
          <a>Create post</a>
        </Link>
        {posts.map(post => 
          {
            if (expiresInSeconds(post.expires_at) < 1) {
              return null
            }
            return (
              <article key={post.id}>
                <h2>{post.title}</h2>
                <p>{post.content}</p>
                <p>{expiresInSeconds(post.expires_at)} seconds to expire</p>
                <button onClick={() => increaseTime(post.id)}>Vote</button>
              </article>
            )
          }
        )}
      </main>
    </div>
  )
}
