import { useState, useEffect } from 'react'
import axios from 'axios'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [posts, setPosts] = useState([])

  useEffect(() => {
    axios.get('http://localhost:3000/posts')
      .then((response) => {
        setPosts(response.data)
        console.log(response.data)
      })
      .catch((err) => {
        console.log(err);
      })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Basic Reddit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {posts.map(post => 
          <article key={post.index}>
            <h2>{post.title}</h2>
            <p>{post.content}</p>
          </article>
        )}
      </main>
    </div>
  )
}
